### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by vthemelis**
```
npm ci
npm run test
npm run lint
```
work but tests are actually failing. I can fix the tests in a separate PR.

### CODE REVIEW

**Comment by vthemelis** [comment]
@AdrieanKhisbe , can I have a review on this?

**Comment by vthemelis** [comment]
@sipi , could I have a review on this? If it makes it easier I could add a GitHub action to build this project?

**Comment by vthemelis** [comment]
GitHub action added here: https://github.com/vscode-org-mode/vscode-org-mode/pull/217

**Review by zetashift — APPROVED** [review]

**Comment by zetashift** [comment]
Thank you for this! Seems mostly linting, but this is very much appreciated :D

**Comment by vthemelis** [comment]
Thanks for the review @zetashift . Could we merge this?

**Pull request merged**
